from pydantic import BaseModel, Field
from typing import Optional
from enum import Enum

class ScrewType(str, Enum):
    A = "Screw Type A"

class MachineClass(str, Enum):
    T90 = "90T"
    T120 = "120T"
    T160 = "160T"
    T200 = "200T"
    T250 = "250T"
    T280 = "280T"
    T380 = "380T"
    T450 = "450T"
    T470 = "470T"
    T800 = "800T"

# Industrial Machine Catalog - Haitian-style specifications
MACHINE_SPECS_CATALOG = {
    "90T": {
        "machine_class": "90T",
        "tonnage": 90,
        "clamping_force_kn": 900,
        "tie_bar_distance_width": 310,
        "tie_bar_distance_height": 310,
        "platen_size_width": 410,
        "platen_size_height": 410,
        "mold_thickness_min": 150,
        "mold_thickness_max": 350,
        "max_daylight": 700,
        "ejector_force_kn": 20,
        "shot_volume_max": 127,
        "screw_diameter": 30,
        "injection_pressure_max": 163,
        "motor_power_kw": 7.5,
        "pump_power_kw": 5.5,
        "ideal_cycle_time_sec": 10,
        "weight_kg": 3200,
        "screw_type": ScrewType.A,
    },
    "120T": {
        "machine_class": "120T",
        "tonnage": 120,
        "clamping_force_kn": 1200,
        "tie_bar_distance_width": 370,
        "tie_bar_distance_height": 370,
        "platen_size_width": 510,
        "platen_size_height": 510,
        "mold_thickness_min": 200,
        "mold_thickness_max": 450,
        "max_daylight": 850,
        "ejector_force_kn": 25,
        "shot_volume_max": 180,
        "screw_diameter": 35,
        "injection_pressure_max": 159,
        "motor_power_kw": 11,
        "pump_power_kw": 7.5,
        "ideal_cycle_time_sec": 12,
        "weight_kg": 4500,
        "screw_type": ScrewType.A,
    },
    "160T": {
        "machine_class": "160T",
        "tonnage": 160,
        "clamping_force_kn": 1600,
        "tie_bar_distance_width": 420,
        "tie_bar_distance_height": 420,
        "platen_size_width": 560,
        "platen_size_height": 560,
        "mold_thickness_min": 200,
        "mold_thickness_max": 500,
        "max_daylight": 950,
        "ejector_force_kn": 35,
        "shot_volume_max": 270,
        "screw_diameter": 40,
        "injection_pressure_max": 158,
        "motor_power_kw": 15,
        "pump_power_kw": 11,
        "ideal_cycle_time_sec": 14,
        "weight_kg": 5800,
        "screw_type": ScrewType.A,
    },
    "200T": {
        "machine_class": "200T",
        "tonnage": 200,
        "clamping_force_kn": 2000,
        "tie_bar_distance_width": 470,
        "tie_bar_distance_height": 470,
        "platen_size_width": 640,
        "platen_size_height": 640,
        "mold_thickness_min": 250,
        "mold_thickness_max": 550,
        "max_daylight": 1050,
        "ejector_force_kn": 40,
        "shot_volume_max": 383,
        "screw_diameter": 45,
        "injection_pressure_max": 155,
        "motor_power_kw": 18.5,
        "pump_power_kw": 15,
        "ideal_cycle_time_sec": 16,
        "weight_kg": 7200,
        "screw_type": ScrewType.A,
    },
    "250T": {
        "machine_class": "250T",
        "tonnage": 250,
        "clamping_force_kn": 2500,
        "tie_bar_distance_width": 520,
        "tie_bar_distance_height": 520,
        "platen_size_width": 710,
        "platen_size_height": 710,
        "mold_thickness_min": 280,
        "mold_thickness_max": 600,
        "max_daylight": 1150,
        "ejector_force_kn": 50,
        "shot_volume_max": 519,
        "screw_diameter": 50,
        "injection_pressure_max": 154,
        "motor_power_kw": 22,
        "pump_power_kw": 18.5,
        "ideal_cycle_time_sec": 18,
        "weight_kg": 9500,
        "screw_type": ScrewType.A,
    },
    "280T": {
        "machine_class": "280T",
        "tonnage": 280,
        "clamping_force_kn": 2800,
        "tie_bar_distance_width": 560,
        "tie_bar_distance_height": 560,
        "platen_size_width": 760,
        "platen_size_height": 760,
        "mold_thickness_min": 300,
        "mold_thickness_max": 650,
        "max_daylight": 1250,
        "ejector_force_kn": 55,
        "shot_volume_max": 648,
        "screw_diameter": 55,
        "injection_pressure_max": 152,
        "motor_power_kw": 30,
        "pump_power_kw": 22,
        "ideal_cycle_time_sec": 20,
        "weight_kg": 11000,
        "screw_type": ScrewType.A,
    },
    "380T": {
        "machine_class": "380T",
        "tonnage": 380,
        "clamping_force_kn": 3800,
        "tie_bar_distance_width": 630,
        "tie_bar_distance_height": 630,
        "platen_size_width": 860,
        "platen_size_height": 860,
        "mold_thickness_min": 350,
        "mold_thickness_max": 750,
        "max_daylight": 1400,
        "ejector_force_kn": 75,
        "shot_volume_max": 916,
        "screw_diameter": 60,
        "injection_pressure_max": 150,
        "motor_power_kw": 37,
        "pump_power_kw": 30,
        "ideal_cycle_time_sec": 24,
        "weight_kg": 15000,
        "screw_type": ScrewType.A,
    },
    "450T": {
        "machine_class": "450T",
        "tonnage": 450,
        "clamping_force_kn": 4500,
        "tie_bar_distance_width": 730,
        "tie_bar_distance_height": 730,
        "platen_size_width": 1000,
        "platen_size_height": 1000,
        "mold_thickness_min": 400,
        "mold_thickness_max": 850,
        "max_daylight": 1600,
        "ejector_force_kn": 90,
        "shot_volume_max": 1290,
        "screw_diameter": 70,
        "injection_pressure_max": 148,
        "motor_power_kw": 45,
        "pump_power_kw": 37,
        "ideal_cycle_time_sec": 28,
        "weight_kg": 19000,
        "screw_type": ScrewType.A,
    },
    "470T": {
        "machine_class": "470T",
        "tonnage": 470,
        "clamping_force_kn": 4700,
        "tie_bar_distance_width": 760,
        "tie_bar_distance_height": 760,
        "platen_size_width": 1050,
        "platen_size_height": 1050,
        "mold_thickness_min": 450,
        "mold_thickness_max": 900,
        "max_daylight": 1700,
        "ejector_force_kn": 100,
        "shot_volume_max": 1465,
        "screw_diameter": 75,
        "injection_pressure_max": 146,
        "motor_power_kw": 55,
        "pump_power_kw": 45,
        "ideal_cycle_time_sec": 30,
        "weight_kg": 22000,
        "screw_type": ScrewType.A,
    },
    "800T": {
        "machine_class": "800T",
        "tonnage": 800,
        "clamping_force_kn": 8000,
        "tie_bar_distance_width": 950,
        "tie_bar_distance_height": 950,
        "platen_size_width": 1350,
        "platen_size_height": 1350,
        "mold_thickness_min": 500,
        "mold_thickness_max": 1100,
        "max_daylight": 2100,
        "ejector_force_kn": 150,
        "shot_volume_max": 2800,
        "screw_diameter": 90,
        "injection_pressure_max": 140,
        "motor_power_kw": 75,
        "pump_power_kw": 55,
        "ideal_cycle_time_sec": 40,
        "weight_kg": 35000,
        "screw_type": ScrewType.A,
    }
}

# Zone classification for factory layout
class MachineZone(str, Enum):
    HEAVY = "heavy"      # >= 380T
    MEDIUM = "medium"    # 160T - 380T
    LIGHT = "light"     # < 160T

def get_machine_zone(tonnage: int) -> MachineZone:
    if tonnage >= 380:
        return MachineZone.HEAVY
    elif tonnage >= 160:
        return MachineZone.MEDIUM
    else:
        return MachineZone.LIGHT